[project]
name = "iron-pgn-parser"
version = "0.1.2"
description = "A faster PGN parser made in rust"
readme = "README.md"
authors = [
    { name = "Louis Turpault", email = "louis.turpault@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chess>=1.11.2",
    "maturin>=1.15.0",
]

[project.scripts]
iron-pgn-parser = "iron_pgn_parser:main"

[build-system]
requires = ["maturin>=1.15.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "src/python"
module-name = "chess_bridge.native"

